"""create feature usage analytics table

Revision ID: bf584716386e
Revises: 79a050b6961b
Create Date: 2026-09-23 17:35:46.504337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf584716386e'
down_revision: Union[str, Sequence[str], None] = '79a050b6961b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_flag_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('rollout_id', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flags.id'], ),
    sa.ForeignKeyConstraint(['rollout_id'], ['feature_rollouts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_usage_environment_id'), 'feature_usage', ['environment_id'], unique=False)
    op.create_index(op.f('ix_feature_usage_evaluated_at'), 'feature_usage', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_feature_usage_feature_flag_id'), 'feature_usage', ['feature_flag_id'], unique=False)
    op.create_index(op.f('ix_feature_usage_user_id'), 'feature_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_usage_user_id'), table_name='feature_usage')
    op.drop_index(op.f('ix_feature_usage_feature_flag_id'), table_name='feature_usage')
    op.drop_index(op.f('ix_feature_usage_evaluated_at'), table_name='feature_usage')
    op.drop_index(op.f('ix_feature_usage_environment_id'), table_name='feature_usage')
    op.drop_table('feature_usage')
    # ### end Alembic commands ###
